### ISSUE TITLE
what dose it mean?

### ISSUE THREAD

**Issue by rm-killer** [KenSukiVN/gensyn-node#1]
![Image](https://github.com/user-attachments/assets/777587e9-3772-4050-9d3a-2e42020c2cc2)
Bro can you tell me what dose this mean?
first line copys the old sh to new sh file? right?
then i have to copy the code you provided in the first lines of my new Sh file?
all of the codes than is provided by you or just the first 3 lines?

**Comment by quangtuyen88** [comment]
I have updated readme @rm-killer . you can check it again

**Comment by rm-killer** [comment]
i read it. but still have problem understanding it. in step 3. it cp original sh file to new sh file? correct?
and then what dose the command do that you want us to run???? shouldn't we modify the new sh file directly??? cause the way you said it it like runing code on termial. but i think we have to modify the sh file.!!! no?
